<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const TIME = 300;
        const TIME2 = 200;

        function repeat(count) {
            return new Promise((resolve, reject) => {
                if (count >= 20) {
                    reject(new Error('Too many iterations in f1, max 20'));
                }
                setTimeout(() => {
                    resolve();
                }, count * TIME);
            });
        }

        function repeat2(count) {
            return new Promise((resolve, reject) => {
                if (count >= 30) {
                    reject(new Error('Too many iterations in f2, max 30'));
                }
                setTimeout(() => {
                    resolve();
                }, count * TIME2);
            });
        }

        //EXAMPLE 1
        // console.log('Start');
        // repeat(10).then(() => {
        //     console.log(`Repeated by first func.`);  
        // })

        //EXAMPLE 2

        // console.log('Start');
        //     repeat(10).then(() => {
        //         console.log(`Repeated by first func.`);  
        //         return repeat2(5);
        //     }).then (() => {
        //         console.log(`Repeated by second func.`);  
        //     })


        // EXAMPLE 3

        // console.log('Start');
        // repeat(10).then(() => {
        //     console.log(`Repeated by first func.`);
        //     return repeat2(35);
        // }).then(() => {
        //     console.log(`Repeated by second func.`);
        // }).catch((err) => {
        //     console.log(`${err}. Can't continue...`);
        // })

        // EXAMPLE 4

        async function myIterations() {
            try {
                console.log('Start');
                await repeat(10);
                console.log(`Counted by first func.`);
                await repeat2(40);
                console.log(`Counted by second func.`);
                return true;
            } catch (err) {
                console.log(`${err}. Can't continue...`);
                return false;
            }
        }

        myIterations().then((res) => {
            console.log(res);
        })
    </script>
</body>

</html>
